// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVq5q7DxJILJxaWNsggFwvqqXuE9QeQU',
    appId: '1:212555878819:web:2875f38c14cecae50c4a16',
    messagingSenderId: '212555878819',
    projectId: 'readlog-e631e',
    authDomain: 'readlog-e631e.firebaseapp.com',
    storageBucket: 'readlog-e631e.firebasestorage.app',
    measurementId: 'G-7NDTNF6WXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0K1UHAQzLUJUa4nBNfra9fBIwAOnLL6Y',
    appId: '1:212555878819:android:d32e226b99ebaf600c4a16',
    messagingSenderId: '212555878819',
    projectId: 'readlog-e631e',
    storageBucket: 'readlog-e631e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfeaMrmrggpdgv3HCH3zWzXAPVe_g-rI',
    appId: '1:212555878819:ios:ce0cd98f9338a66d0c4a16',
    messagingSenderId: '212555878819',
    projectId: 'readlog-e631e',
    storageBucket: 'readlog-e631e.firebasestorage.app',
    iosBundleId: 'com.example.readlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfeaMrmrggpdgv3HCH3zWzXAPVe_g-rI',
    appId: '1:212555878819:ios:ce0cd98f9338a66d0c4a16',
    messagingSenderId: '212555878819',
    projectId: 'readlog-e631e',
    storageBucket: 'readlog-e631e.firebasestorage.app',
    iosBundleId: 'com.example.readlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVq5q7DxJILJxaWNsggFwvqqXuE9QeQU',
    appId: '1:212555878819:web:b2d19e5cef6f1e8a0c4a16',
    messagingSenderId: '212555878819',
    projectId: 'readlog-e631e',
    authDomain: 'readlog-e631e.firebaseapp.com',
    storageBucket: 'readlog-e631e.firebasestorage.app',
    measurementId: 'G-J0CHFCTLVG',
  );
}
